spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10

springdoc:
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:false}

logging:
  level:
    root: info
