spring:
  application:
    name: rain-butler
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/rainbutler}
    username: ${DB_USERNAME:rainbutler}
    password: ${DB_PASSWORD:rainbutler}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update} # ERD 확정 후 Flyway 마이그레이션으로 전환 예정
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

springdoc:
  swagger-ui:
    path: /swagger-ui
