
CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "provider" varchar NOT NULL,
  "provider_id" varchar NOT NULL,
  "nickname" varchar NOT NULL,
  "real_name" varchar,
  "identity_verified_at" timestamp,
  "email" varchar,
  "profile_image" varchar,
  "role" varchar NOT NULL,
  "point" int NOT NULL DEFAULT 0,
  "level" int NOT NULL DEFAULT 1,
  "latitude" double precision,
  "longitude" double precision,
  "location_updated_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "push_subscription" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "endpoint" text UNIQUE NOT NULL,
  "p256dh" varchar NOT NULL,
  "auth" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "photo_hash" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "hash" varchar(64) UNIQUE NOT NULL,
  "source_table" varchar NOT NULL,
  "source_id" bigint NOT NULL,
  "photo_role" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "point_history" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "source_type" varchar NOT NULL,
  "source_id" bigint NOT NULL,
  "amount" int NOT NULL,
  "type" varchar NOT NULL,
  "description" varchar,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "drain" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "registered_by" bigint,
  "latitude" double precision NOT NULL,
  "longitude" double precision NOT NULL,
  "photo_url" varchar NOT NULL,
  "dirt_level" int NOT NULL,
  "adoption_status" varchar NOT NULL,
  "status" varchar NOT NULL,
  "is_risk" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "adoption" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "drain_id" bigint NOT NULL,
  "cleaning_id" bigint UNIQUE NOT NULL,
  "nickname" varchar NOT NULL,
  "status" varchar NOT NULL,
  "release_reason" varchar,
  "level" int NOT NULL DEFAULT 1,
  "score" int NOT NULL DEFAULT 0,
  "ignore_count" int NOT NULL DEFAULT 0,
  "adopted_at" timestamp NOT NULL,
  "last_managed_at" timestamp,
  "next_management_at" timestamp,
  "released_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "management_log" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "adoption_id" bigint NOT NULL,
  "request_id" bigint UNIQUE,
  "type" varchar NOT NULL,
  "action_type" varchar NOT NULL,
  "status" varchar NOT NULL,
  "review_status" varchar NOT NULL,
  "reviewed_by" bigint,
  "reviewed_at" timestamp,
  "before_photo_url" varchar,
  "after_photo_url" varchar,
  "dirt_level" int,
  "ai_confidence" numeric(3,2),
  "memo" varchar,
  "latitude" double precision,
  "longitude" double precision,
  "location_mismatch" boolean NOT NULL DEFAULT false,
  "managed_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "cleaning" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "drain_id" bigint NOT NULL,
  "request_id" bigint UNIQUE,
  "type" varchar NOT NULL,
  "before_photo_url" varchar NOT NULL,
  "dirt_level" int,
  "dirt_confidence" numeric(3,2),
  "status" varchar NOT NULL,
  "review_status" varchar NOT NULL,
  "reviewed_by" bigint,
  "reviewed_at" timestamp,
  "latitude" double precision NOT NULL,
  "longitude" double precision NOT NULL,
  "location_mismatch" boolean NOT NULL DEFAULT false,
  "started_at" timestamp NOT NULL,
  "completed_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "ai_verification" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cleaning_id" bigint,
  "management_log_id" bigint,
  "attempt_no" int NOT NULL,
  "after_photo_url" varchar NOT NULL,
  "result" varchar NOT NULL,
  "confidence" numeric(3,2),
  "reason" varchar,
  "verified_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "tool_box" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "latitude" double precision NOT NULL,
  "longitude" double precision NOT NULL,
  "total_count" int NOT NULL,
  "available_count" int NOT NULL,
  "status" varchar NOT NULL,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "tool_rental" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "tool_box_id" bigint NOT NULL,
  "status" varchar NOT NULL,
  "rented_at" timestamp NOT NULL,
  "returned_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "rain_forecast" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rain_date" date NOT NULL,
  "rain_start_at" timestamp NOT NULL,
  "pop" int NOT NULL,
  "pcp_mm" numeric(5,2) NOT NULL,
  "status" varchar NOT NULL,
  "is_simulated" boolean NOT NULL DEFAULT false,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "inspection_request" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "forecast_id" bigint NOT NULL,
  "drain_id" bigint NOT NULL,
  "adoption_id" bigint,
  "substitute_user_id" bigint,
  "status" varchar NOT NULL,
  "reply" varchar,
  "sent_at" timestamp NOT NULL,
  "reply_deadline_at" timestamp NOT NULL,
  "replied_at" timestamp,
  "opened_at" timestamp,
  "claimed_at" timestamp,
  "completed_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "report" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "drain_id" bigint NOT NULL,
  "processed_by" bigint,
  "type" varchar NOT NULL,
  "description" varchar,
  "photo_url" varchar,
  "new_latitude" double precision,
  "new_longitude" double precision,
  "status" varchar NOT NULL,
  "admin_comment" varchar,
  "resolved_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE TABLE "notification" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "request_id" bigint,
  "adoption_id" bigint,
  "type" varchar NOT NULL,
  "title" varchar NOT NULL,
  "body" varchar NOT NULL,
  "sent_at" timestamp,
  "read_at" timestamp,
  "created_at" timestamp NOT NULL,
  "updated_at" timestamp NOT NULL,
  "deleted_at" timestamp
);

CREATE UNIQUE INDEX ON "users" ("provider", "provider_id");

CREATE UNIQUE INDEX ON "inspection_request" ("forecast_id", "drain_id");

COMMENT ON COLUMN "users"."provider" IS 'KAKAO';

COMMENT ON COLUMN "users"."provider_id" IS '카카오 회원번호';

COMMENT ON COLUMN "users"."real_name" IS '실명 (봉사 확인서용)';

COMMENT ON COLUMN "users"."identity_verified_at" IS '실명 인증 시각';

COMMENT ON COLUMN "users"."role" IS 'ADMIN / CITY_OFFICIAL / USER';

COMMENT ON COLUMN "users"."point" IS 'point_history 합계';

COMMENT ON COLUMN "users"."level" IS '사용자 전체 활동 레벨';

COMMENT ON COLUMN "users"."latitude" IS '활동 위치 - 대신 점검 대상 판정';

COMMENT ON COLUMN "users"."location_updated_at" IS '활동 위치 갱신 시각';

COMMENT ON COLUMN "photo_hash"."hash" IS 'SHA-256 - 같은 사진 재사용 차단';

COMMENT ON COLUMN "photo_hash"."source_table" IS 'cleaning / management_log / ai_verification / report / drain';

COMMENT ON COLUMN "photo_hash"."photo_role" IS 'BEFORE / AFTER / REPORT / DRAIN';

COMMENT ON COLUMN "point_history"."source_type" IS 'CLEANING / MANAGEMENT / REPORT';

COMMENT ON COLUMN "point_history"."type" IS 'EARN / REVOKE';

COMMENT ON COLUMN "drain"."registered_by" IS '등록자 (현장 조사한 관리자 or 제보자)';

COMMENT ON COLUMN "drain"."photo_url" IS '최신 현장 사진 (청소·관리 때마다 갱신)';

COMMENT ON COLUMN "drain"."dirt_level" IS '최신 더러움 단계 1 / 2 / 3';

COMMENT ON COLUMN "drain"."adoption_status" IS 'AVAILABLE / ADOPTED';

COMMENT ON COLUMN "drain"."status" IS 'ACTIVE / PENDING(신규 제보 승인 대기) / REMOVED';

COMMENT ON COLUMN "drain"."is_risk" IS '위험 배수구 - 현장 조사 때 등록하면서 지정';

COMMENT ON TABLE "adoption" IS '사용자당 ACTIVE 최대 3개 (서비스 로직) / 배수구당 ACTIVE 1개 (UNIQUE drain_id WHERE status=ACTIVE)';

COMMENT ON COLUMN "adoption"."cleaning_id" IS '입양 조건 청소 (청소 1건 = 입양 1건)';

COMMENT ON COLUMN "adoption"."nickname" IS '배수구에 붙인 이름';

COMMENT ON COLUMN "adoption"."status" IS 'ACTIVE / RELEASED';

COMMENT ON COLUMN "adoption"."release_reason" IS 'MOVED / NO_TIME / OTHER / AUTO(35일 미관리)';

COMMENT ON COLUMN "adoption"."level" IS '배수구 캐릭터 레벨 - 입양자 바뀌면 초기화';

COMMENT ON COLUMN "adoption"."ignore_count" IS '비 예보 요청 연속 무응답';

COMMENT ON COLUMN "adoption"."last_managed_at" IS '마지막 점검일 - 35일 미점검 자동 파양 판정';

COMMENT ON COLUMN "adoption"."next_management_at" IS '다음 관리 예정일 (14일)';

COMMENT ON COLUMN "management_log"."request_id" IS '비 예보 요청으로 한 관리면 연결';

COMMENT ON COLUMN "management_log"."type" IS 'REGULAR(정기 점검) / RAIN(비 예보 점검 - request_id 있음)';

COMMENT ON COLUMN "management_log"."action_type" IS 'INSPECTION(살펴보기만) / CLEANING(청소까지)';

COMMENT ON COLUMN "management_log"."status" IS 'SUBMITTED / VERIFIED / FAILED';

COMMENT ON COLUMN "management_log"."review_status" IS 'NOT_REQUIRED / PENDING / APPROVED / REJECTED';

COMMENT ON COLUMN "management_log"."dirt_level" IS 'AI 더러움 단계 1~3';

COMMENT ON COLUMN "management_log"."latitude" IS '촬영 위치';

COMMENT ON COLUMN "management_log"."location_mismatch" IS '50m 이상';

COMMENT ON COLUMN "cleaning"."request_id" IS '대신 점검이면 연결';

COMMENT ON COLUMN "cleaning"."type" IS 'ADOPTION(입양 전 청소) / SUBSTITUTE(대신 점검)';

COMMENT ON COLUMN "cleaning"."dirt_level" IS 'AI가 비포 사진으로 판정한 더러움 1~3';

COMMENT ON COLUMN "cleaning"."status" IS '진행 상태: IN_PROGRESS / VERIFYING / COMPLETED / FAILED';

COMMENT ON COLUMN "cleaning"."review_status" IS 'NOT_REQUIRED / PENDING / APPROVED / REJECTED';

COMMENT ON COLUMN "ai_verification"."cleaning_id" IS 'cleaning_id / management_log_id 중 하나만';

COMMENT ON COLUMN "ai_verification"."result" IS 'PASS / FAIL';

COMMENT ON COLUMN "tool_box"."total_count" IS '구비된 세트 수';

COMMENT ON COLUMN "tool_box"."available_count" IS '대여 시 -1, 반납 시 +1';

COMMENT ON COLUMN "tool_box"."status" IS 'AVAILABLE / ALL_RENTED (available_count = 0)';

COMMENT ON TABLE "tool_rental" IS '빌릴 때 tool_box.available_count -1, 반납할 때 +1 / 1인 1개만 대여 (UNIQUE user_id WHERE status=RENTED) / 빌린 도구함에만 반납';

COMMENT ON COLUMN "tool_rental"."status" IS 'RENTED / RETURNED';

COMMENT ON COLUMN "rain_forecast"."rain_date" IS '비 오는 날';

COMMENT ON COLUMN "rain_forecast"."pop" IS '강수확률 %';

COMMENT ON COLUMN "rain_forecast"."pcp_mm" IS '1시간 강수량';

COMMENT ON COLUMN "rain_forecast"."status" IS 'ACTIVE / CANCELLED';

COMMENT ON COLUMN "rain_forecast"."is_simulated" IS '시연용 가상 예보';

COMMENT ON COLUMN "inspection_request"."adoption_id" IS '입양자에게 간 요청. 미입양 위험 배수구면 null → 바로 대신 점검 공개';

COMMENT ON COLUMN "inspection_request"."substitute_user_id" IS '대신 점검 수락자 (선착순 1명)';

COMMENT ON COLUMN "inspection_request"."status" IS 'SENT / ACCEPTED / OPEN / CLAIMED / COMPLETED / MISSED / CANCELLED';

COMMENT ON COLUMN "inspection_request"."reply" IS 'ACCEPT / DECLINE / null(무응답)';

COMMENT ON COLUMN "inspection_request"."sent_at" IS '전날 06:00 일괄 발송';

COMMENT ON COLUMN "inspection_request"."reply_deadline_at" IS '전날 20:00 - 지나면 대신 점검으로 공개 (점검 마감은 로직에서 처리)';

COMMENT ON COLUMN "report"."processed_by" IS '처리한 시청 관계자·관리자';

COMMENT ON COLUMN "report"."type" IS 'BLOCKAGE / NEW_DRAIN / LOCATION_FIX / REMOVAL';

COMMENT ON COLUMN "report"."new_latitude" IS 'LOCATION_FIX 제보의 새 위치';

COMMENT ON COLUMN "report"."status" IS 'PENDING / APPROVED / REJECTED';

COMMENT ON COLUMN "notification"."type" IS 'RAIN_TOMORROW / SUBSTITUTE_OPEN / MANAGEMENT_DUE / ...';

ALTER TABLE "push_subscription" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "point_history" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "drain" ADD FOREIGN KEY ("registered_by") REFERENCES "users" ("id") ;

ALTER TABLE "adoption" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "adoption" ADD FOREIGN KEY ("drain_id") REFERENCES "drain" ("id") ;

ALTER TABLE "adoption" ADD FOREIGN KEY ("cleaning_id") REFERENCES "cleaning" ("id") ;

ALTER TABLE "management_log" ADD FOREIGN KEY ("adoption_id") REFERENCES "adoption" ("id") ;

ALTER TABLE "management_log" ADD FOREIGN KEY ("request_id") REFERENCES "inspection_request" ("id") ;

ALTER TABLE "management_log" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ;

ALTER TABLE "cleaning" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "cleaning" ADD FOREIGN KEY ("drain_id") REFERENCES "drain" ("id") ;

ALTER TABLE "cleaning" ADD FOREIGN KEY ("request_id") REFERENCES "inspection_request" ("id") ;

ALTER TABLE "cleaning" ADD FOREIGN KEY ("reviewed_by") REFERENCES "users" ("id") ;

ALTER TABLE "ai_verification" ADD FOREIGN KEY ("cleaning_id") REFERENCES "cleaning" ("id") ;

ALTER TABLE "ai_verification" ADD FOREIGN KEY ("management_log_id") REFERENCES "management_log" ("id") ;

ALTER TABLE "tool_rental" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "tool_rental" ADD FOREIGN KEY ("tool_box_id") REFERENCES "tool_box" ("id") ;

ALTER TABLE "inspection_request" ADD FOREIGN KEY ("forecast_id") REFERENCES "rain_forecast" ("id") ;

ALTER TABLE "inspection_request" ADD FOREIGN KEY ("drain_id") REFERENCES "drain" ("id") ;

ALTER TABLE "inspection_request" ADD FOREIGN KEY ("adoption_id") REFERENCES "adoption" ("id") ;

ALTER TABLE "inspection_request" ADD FOREIGN KEY ("substitute_user_id") REFERENCES "users" ("id") ;

ALTER TABLE "report" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "report" ADD FOREIGN KEY ("drain_id") REFERENCES "drain" ("id") ;

ALTER TABLE "report" ADD FOREIGN KEY ("processed_by") REFERENCES "users" ("id") ;

ALTER TABLE "notification" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") ;

ALTER TABLE "notification" ADD FOREIGN KEY ("request_id") REFERENCES "inspection_request" ("id") ;

ALTER TABLE "notification" ADD FOREIGN KEY ("adoption_id") REFERENCES "adoption" ("id") ;

-- ───────── ERD 밖 제약 (부분 인덱스 · CHECK) ─────────
-- 배수구당 진행 중인 입양 1개
CREATE UNIQUE INDEX uq_adoption_active_drain ON "adoption" ("drain_id") WHERE "status" = 'ACTIVE' AND "deleted_at" IS NULL;
-- 1인 1개 대여
CREATE UNIQUE INDEX uq_tool_rental_active_user ON "tool_rental" ("user_id") WHERE "status" = 'RENTED' AND "deleted_at" IS NULL;
-- 더러움 단계 1~3
ALTER TABLE "drain" ADD CONSTRAINT ck_drain_dirt_level CHECK ("dirt_level" BETWEEN 1 AND 3);
-- 도구함 수량은 0 ~ total
ALTER TABLE "tool_box" ADD CONSTRAINT ck_tool_box_count CHECK ("available_count" BETWEEN 0 AND "total_count");
-- 비 예보 점검이면 request_id 필수, 정기 점검이면 없음
ALTER TABLE "management_log" ADD CONSTRAINT ck_management_log_type CHECK (("type" = 'RAIN') = ("request_id" IS NOT NULL));
-- AI 인증은 청소 또는 관리 기록 중 하나에만 붙는다
ALTER TABLE "ai_verification" ADD CONSTRAINT ck_ai_verification_target CHECK (num_nonnulls("cleaning_id", "management_log_id") = 1);

-- ───────── 조회용 인덱스 ─────────
CREATE INDEX idx_drain_location ON "drain" ("latitude", "longitude");
CREATE INDEX idx_notification_user_read ON "notification" ("user_id", "read_at");
CREATE INDEX idx_inspection_request_status ON "inspection_request" ("status");
CREATE INDEX idx_adoption_user_status ON "adoption" ("user_id", "status");
